### ISSUE TITLE
lru-cache to v7.4.0 and remove deprecated `maxAge` option

### ISSUE THREAD

**Issue by radomird** [nearform/get-jwks#117]
Dependabot is failing to upgrade the `lru-cach` library from 6.0.0 to 7.4.0 because the tests fail.
Check the failing PR here: https://github.com/nearform/get-jwks/pull/116

**Comment by simoneb** [comment]
for the future. we don't actually need an issue to fix dependabot broken PRs. we can just use the PR as the issue and push code to it

**Comment by radomird** [comment]
The issue happens because v7.4.0 deprecates `maxAge` option and `ttl` should be used instead. I'll close the PR and open a new one where I'll update the code and docs.
