### ISSUE TITLE
Feature request: More specific errors

### ISSUE THREAD

**Issue by pigulla** [nearform/get-jwks#156]
Currently, `get-jwks` throws generic instances of `Error` and all details are "hidden" in the message (and are thus not easily accessible). This is problematic because it lumps together all errors that can potentially occur:

- upstream errors (e.g., the discovery endpoint returns a 503)
- errors caused by the library itself (not really an issue here as far as I can tell)
- downstream errors (errors for which arguably the client is responsible, e.g. `JWK_NOT_FOUND`)

This matters because the HTTP status code returned to the client should indicate the root cause and be 502, 500 and 400 (or 401), respectively. Mapping this correctly is currently not feasible.

I propose to  use the [`code`](https://nodejs.org/api/errors.html#errorcode) property to convey that information. We could, at least in part, use the keys in the [message mapping](https://github.com/nearform/get-jwks/blob/main/src/get-jwks.js#L7) for that. Defining a new error class, say `JwksError`, might also be beneficial to simplify user land code.

I'm more than happy to whip up a PR if you are in principle willing to add such a feature.

**Comment by simoneb** [comment]
Thanks for raising this. Absolutely, a PR would be much appreciated

**Comment by mcollina** [comment]
I'd recommend using https://github.com/fastify/fastify-error or analog
