### ISSUE TITLE
use stale on fail

### ISSUE THREAD

**Issue by mcollina** [nearform/get-jwks#20]
If we fail to fetch() the URL, it is better to use a stale key if it is missing.

**Comment by simoneb** [comment]
@mcollina how do you recommend this is implemented? with the current caching mechanism once an item is gone it's gone, no way to get it back. were you thinking about a second cache of stale items? note that tiny-lru has no hooks so we don't know when something is evicted because stale

**Comment by mcollina** [comment]
Maybe we should change the cache implementation with something else, or use two cashes.
