### ISSUE TITLE
Support * in allowed domains or callback

### ISSUE THREAD

**Issue by CyanoFresh** [nearform/get-jwks#226]
Hi!
First of all, thanks for the great library!
Feature request:
Domains option doesn't mean url domain, it means the whole issuer address. This is a problem for Keycloak: each realm has different issuer address: `http://localhost:8080/realms/REALM_NAME`. 
This option doesn't support asterisk * or wildcard, so I cannot trust any certificate from my keycloak instance, I need to specify the exact one. Would be nice if you add a `checkIssuer():bool` function or a wildcard support

**Comment by simoneb** [comment]
@eugenio-oddone please remember to link issues to PRs so they are closed when PRs are merged
