### ISSUE TITLE
Using the `n` prop in a JWK

### ISSUE THREAD

**Issue by conor909** [nearform/get-jwks#27]
After introducing the `jwk-to-pem` package to format the keys for use with cognito and other auth service providers, we rely on the `n` property on a JWKS key.  The `n` property contains the value for the RSA public key and is represented as a Base64urlUInt-encoded value.  The following note has been taken from the [RSA Public Keys spec](https://tools.ietf.org/html/rfc7518#page-30) regarding the `n` property:

> Note that implementers have found that some cryptographic libraries
   prefix an extra zero-valued octet to the modulus representations they
   return, for instance, returning 257 octets for a 2048-bit key, rather
   than 256.  Implementations using such libraries will need to take
   care to omit the extra octet from the base64url-encoded
   representation.

We'll need to confirm the `jwk-to-pem` package handles this to support any services that may need it, or any of our own future implementations.

**Comment by simoneb** [comment]
This may be an entirely legitimate concern but I wonder why we have it. I mean, even though I guess we didn't study the spec or look into what jwk-to-pem does, why are we thinking that this may not be supported?

**Comment by conor909** [comment]
Yes just for those reasons.  Previously to introducing `jwk-to-pem`, we only used the `x5c` property on the `jwk` to return the secret.  Now it works differently, we only use the `n` property, and I haven't looked into exactly what `jwk-to-pem` does with that, so since reading about this caveat for implementers, I wanted to make a note of it somewhere.

**Comment by simoneb** [comment]
Closing as stale
