### ISSUE TITLE
Security vulnerability introduced by jwk-to-pem peer dependency

### ISSUE THREAD

**Issue by phabreeze** [nearform/get-jwks#304]
There is currently a critical security vulnerability with one of `jwk-to-pem` peer dependencies (`elliptic`)
![image](https://github.com/user-attachments/assets/c62bd4da-00e3-4459-b226-1b890645840b)

node v20.11.1
get-jwks v.9.0.2

**Comment by Eomm** [comment]
The dependency is not pinned, running `npm update --save` or `npm audit --fix` will fix it because it has already been fixed.

https://security.snyk.io/package/npm/elliptic
