### ISSUE TITLE
Configure auto-landing for dependabot PRs

### ISSUE THREAD

**Issue by mcollina** [nearform/get-jwks#33]
Use https://github.com/fastify/github-action-merge-dependabot

**Comment by simoneb** [comment]
I would like to start considering a better solution for the automerge behavior. That action has the known limitation that merges done by the action will skip CI, this is a documented behavior which is not easy to workaround. I would like to start considering the built-in GitHub automerge instead, for repositories where it makes sense. This is one of them.

**Comment by simoneb** [comment]
This is already done, closing
