### ISSUE TITLE
jwks Endpoint is not configurable and hardcoded

### ISSUE THREAD

**Issue by tobsenll** [nearform/get-jwks#43]
We are using keycloak and the jwks_uri points not to .well-known/jwks.json but to another uri.

This line is hardcoding it https://github.com/nearform/get-jwks/blob/c41ba3be28da8f3bcacde75ab1dce3af38cae436/src/get-jwks.js#L68

As far as I understand is that "jwks_uri" is a required property and should be used in the retrieveJwk.

Will try to setup a PR for that

**Comment by mcollina** [comment]
Awesome!

**Comment by simoneb** [comment]
Closed via #44
