### ISSUE TITLE
Support non standard JWKS paths

### ISSUE THREAD

**Issue by alex-rieger** [nearform/get-jwks#52]
Hi,

is it possible to update plugins options to allow passing a custom `path` to the remote JWKS keys? Currently it always points to `.well-known/jwks.json` which does not work for every project.

Will be glad to help with the PR.
Thanks for this cool library.

**Comment by simoneb** [comment]
@alex-rieger I transfered the issue to the get-jwks repo

**Comment by simoneb** [comment]
@alex-rieger is this something you'd be interested in sending a PR for?
